create database customer;
use customer;
SELECT * FROM data limit 10;
#What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) from data group by gender;

#Which customers used a discount but still spent more than the average purchase amount?
select customer_id from data where discount_applied="yes" and purchase_amount > (select avg(purchase_amount) from data);

#Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as review from data group by item_purchased order by review desc limit 5;

#Which 5 products have the highest percentage of purchases with discounts applied?

select shipping_type, avg(purchase_amount) as comp from data WHERE shipping_type IN ('Standard', 'Express') group by shipping_type;

#Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers.
select subscription_status, avg(purchase_amount), sum(purchase_amount) from data group by subscription_status;

#Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, count(*), 
SUM(CASE WHEN discount_applied='Yes'
THEN 1 ELSE 0
END), sum(CASE WHEN discount_applied='Yes'
THEN 1 ELSE 0 end )*100.0 / count(*) as discount
from data group by item_purchased order by discount desc limit 5;

#Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    
    COUNT(*) AS total_customers

FROM data

GROUP BY
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END;
    
    #What are the top 3 most purchased products within each category?
  WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM data
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

#Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM data
WHERE previous_purchases > 5
GROUP BY subscription_status;

#what is the revenue conribution of each age group?
select age_group, sum(purchase_amount) from data group by age_group;

SELECT user, host, plugin
FROM mysql.user
WHERE user = 'root';

CREATE USER 'powerbi_user'@'localhost'
IDENTIFIED BY 'Asha@251121';

GRANT SELECT ON customer.* TO 'powerbi_user'@'localhost';

FLUSH PRIVILEGES;


CREATE USER 'powerbi_user'@'localhost'
IDENTIFIED BY 'Asha@251121';

GRANT SELECT ON customer.* TO 'powerbi_user'@'localhost';